version: '3.9'

services:
  web:
    build: ./average_forecast
    command: >
      sh -c "
        python manage.py runserver
      "
    volumes:
      - ./average_forecast:/average_forecast
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: 
      context: ./average_forecast
    command: celery -A core worker -l debug
    volumes:
      - ./average_forecast:/average_forecast
    env_file:
      - .env
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine