version: '3.9'

services:
  web:
    build: 
      context: .
    volumes:
      - ./:/code
    # command: python average_forecast/manage.py runserver
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - redis

  celery:
    build: 
      context: .
    command: sh -c "cd average_forecast && celery --app average_forecast worker --loglevel=info --logfile=logs/celery.log"
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
  
  dashboard:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True
    volumes:
      - ./:/code
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - celery
