version: '3.9'

services:
  web:
    build: ./average_forecast
    command: >
      sh -c "
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./:/average_forecast
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - redis

  celery:
    build: 
      context: ./average_forecast
    command: celery --app average_forecast worker --loglevel=info --logfile=logs/celery.log 
    volumes:
      - ./average_forecast:/average_forecast
    env_file:
      - .env
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
  
  dashboard:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True
    volumes:
      - ./average_forecast:/average_forecast
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - celery