# Generated by Django 4.0.6 on 2022-07-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of place')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Source_name')),
                ('url', models.URLField(verbose_name='Source API url')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of forecast')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='Air temperature (C)')),
                ('condition', models.CharField(blank=True, max_length=30, null=True, verbose_name='Weather condition')),
                ('wind_direction', models.IntegerField(blank=True, null=True, verbose_name='Wind direction')),
                ('wind_speed', models.IntegerField(blank=True, null=True, verbose_name='Wind speed (m/s)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='Humidity')),
                ('pressure', models.IntegerField(blank=True, null=True, verbose_name='Pressure')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.place')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.source')),
            ],
        ),
    ]
